name: Dinit on debian-bullseye-amd64 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Debian-bullseye-amd64_build:

    runs-on: ubuntu-latest
    container:
      image: debian:bullseye

    steps:
    - uses: actions/checkout@v3
      with:
        ref: cdbdfec85433d5149c3885a73dfde86eb1bb9ad7
    - name: Getting depends
      run: apt-get update && apt-get install gcc make m4 g++ -y
    - name: Print g++ arch
      run: g++ -dumpmachine
    - name: chmod +x configure
      run: chmod +x ./configs/mconfig.Linux.sh
    - name: configure
      run: ./configs/mconfig.Linux.sh
    - name: Build
      run: make
    - name: Install "file" package via apt-get
      run: apt-get install file -y
    - name: Print compiled file arch
      run: file ./src/dinit
    #- name: Unit tests
    #  run: make check
    - name: Integration tests
      run: make check-igr
